// Interface defining statistics for the Analyzer tool
export interface TitleStats {
  total: number;       // Total number of lines processed
  unique: number;      // Count of unique lines
  duplicates: number;  // Count of duplicate lines found
  processedAt: string; // Timestamp string of when analysis occurred
}

// Interface for items in the frequency map (Analyzer)
export interface FrequencyItem {
  title: string;       // The text content of the line
  count: number;       // How many times it appeared
}

// Interface representing the full result of an Analysis operation
export interface AnalysisResult {
  stats: TitleStats;           // Statistical summary
  uniqueList: string[];        // Array of unique strings
  duplicateList: string[];     // Array of strings that appeared more than once
  frequencyMap: FrequencyItem[]; // Array of items sorted by frequency
}

// Interface representing the result of a Comparison operation
export interface ComparisonResult {
  intersection: string[]; // Items found in BOTH List A and List B
  aOnly: string[];        // Items found ONLY in List A
  bOnly: string[];        // Items found ONLY in List B
  stats: {
    inBoth: number;   // Count of overlapping items
    inAOnly: number;  // Count of unique items in A
    inBOnly: number;  // Count of unique items in B
    totalA: number;   // Total items in original List A
    totalB: number;   // Total items in original List B
  }
}

// Interface for a single topic category generated by AI
export interface TopicCategory {
  name: string;    // The name of the category (e.g., "Technology")
  items: string[]; // List of items belonging to this category
}

// Interface for the final result returned by the AI Service
export interface AIAnalysisResult {
  categories: TopicCategory[]; // Array of generated categories
}

// Enum defining the active view/tool currently displayed in the App
export enum ViewMode {
  ANALYZER = 'analyzer',     // View mode for the Data Analyzer tool
  COMPARATOR = 'comparator', // View mode for the List Comparator tool
  TOPICS = 'topics',         // View mode for the AI Topic Sorter tool
  BATCHER = 'batcher'        // View mode for the Batch Processor tool
}